name: Automerge

on:
 push:
     branches:
       - 'release/*'
env:
  DEFAULT_BRANCH: main
  RELEASE_BRANCH: ${{ github.ref }}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_BRANCH }}
          
      - name: Merge changes from release branche to default branch
        run: |
          git config --global user.email "neelimamaddela95@gmail.com"
          git config --global user.name "Neelima"
          git fetch
          git merge --no-commit --no-ff "${{ env.RELEASE_BRANCH }}"
          if [ -n "$(git status --porcelain)" ]; then
            echo "merge conflict detected in release branch"
            echo "$(git status)"
            echo "Conflict detected in the release branch" | mail -s "Merge conflict detected" neelimamaddela95@gmail.com
            exit 1
          fi
          git commit -m "auto-merge changes from ${{ env.RELEASE_BRANCH }} branch"
          git push origin ${{ env.DEFAULT_BRANCH }}
       
      - name: Check for merge conflicts in default branch
        run: |
          git fetch
          git merge --no-commit --no-ff "${{ env.DEFAULT_BRANCH }}"
          if [ -n "$(git status --porcelain)" ]; then
            echo "merge conflict detected in default branch"
            echo "$(git status)"
            echo "Conflict detected in the default branch" | mail -s "Merge conflict detected" neelimamaddela95@gmail.com
            exit 1
          fi
          git merge --abort
            
      - name: Push changes to default branch
        run: |
           git config --global user.name "Neelima"
           git config --global user.email "neelimamaddela95@gmail.com"
           git commit -m "initial commit"
           git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  send-email:
    needs: [auto-merge]
    runs-on: ubuntu-latest
    
    steps:
      - name: Send email notification
        uses: jakejarvis/send-email-action@master
        with:
          server_address: smtp.gamil.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Merge conflict detected 
          body: "Conflicts detected in the release branch to deafult branch"
          to: neelimamaddela95@gmail.com
