name: Changelog
on:
  workflow_dispatch: {}

jobs:
  Push-artifact:
   runs-on: windows-latest
   steps:
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Current Tag
        run: |  
         $CURRENT_SHA = git rev-parse HEAD
         echo "$CURRENT_SHA=$CURRENT_SHA" >> $env:GITHUB_ENV
         Write-Output "Current Commit SHA: $CURRENT_SHA"  

      - name: Save Current Commit
        run: |
          $CURRENT_SHA = $env:CURRENT_SHA
          $CURRENT_SHA | Out-File -FilePath "Prev_commit.txt"
          Write-Output "Prev_commit.txt updated with: $CURRENT_SHA"
          Get-Content -Path "Prev_commit.txt"


      - name: Display File Contents
        run: |
          if (Test-Path -Path "Prev_commit.txt") {
            Get-Content -Path "Prev_commit.txt"
          } else {
            Write-Output "Prev_commit.txt does not exist."
          }
