name: Push artifact to Confluence
on:
  workflow_dispatch: {}

jobs:
  Push-artifact:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Publish Markdown to Confluence
        uses: markdown-confluence/publish@v5
        with:
          confluenceBaseUrl: https://neelimasudhakar.atlassian.net/wiki
          confluenceParentId: 1867778
          atlassianUserName: NeelimaMaddela
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
   
