name: Push artifact to Confluence
on:
  workflow_dispatch: {}

jobs:
  Push-artifact:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Publish Markdown to Confluence
        uses: TTengs/MarkdownToConfluence@v3
        with:
          fileslocation: './docs'
          should_upload: true
          confluence_url: 'https://neelimasudhakar.atlassian.net/wiki'
          confluence_space_key: '~7120200b04a4666ade43ecb8ed95abf53dd3a4'
          auth_username: NeelimaMaddela
          auth_api_token: ${{ secrets.AUTH_API_TOKEN }}
          is_preview: false
   
