name: Push artifact to Confluence
on:
  workflow_dispatch: {}

jobs:
  Push-artifact:
   runs-on: ubuntu-22.04
   steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: get commits 
        run: |
         echo "Latest commits:" >> /docs/commits.md
         REPO_COMMITS=$(git log --format=%B --since='yesterday' | sort | uniq) 
         echo "Repo 1: $REPO_COMMITS" >> /docs/commits.md

      - name: Update .md File  
        run: |
             git config --global user.email "neelimamaddela95@gmail.com"
             git config --global user.name "Neelima"
             git add /docs/commits.md
             git commit -m "update commits.md with latest commit"
             git push origin main

      - uses: cupcakearmy/confluence-markdown-sync@v1
        with:
          from: './docs/commits.md'
          to: '1867778' # The confluence page id where to write the output
          cloud: neelimasudhakar
          user: neelimasudhakar95@gmail.com
          token: ${{ secrets.AUTH_API_TOKEN }}


      # - name: Publish Markdown to Confluence
      #   uses: TTengs/MarkdownToConfluence@v3
      #   with:
      #     fileslocation: './docs'
      #     should_upload: true
      #     confluence_url: 'https://neelimasudhakar.atlassian.net/wiki'
      #     confluence_space_key: '~7120200b04a4666ade43ecb8ed95abf53dd3a4'
      #     auth_username: NeelimaMaddela
      #     auth_api_token: ${{ secrets.AUTH_API_TOKEN }}
      #     is_preview: false
   
