run-name: test, runnumber - ${{ github.event.inputs.environment }}
'on': 
 workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'development'

jobs:
    deploy:
     runs-on: ubuntu-latest
        
     steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Set Workflow Name
        id: set_workflow_name
        run: echo "workflow_name=test, runnumber - ${{ github.event.inputs.environment }}" >> $GITHUB_ENV
 
      - name: Get Previous Run Number
        id: get_run_number
        if: env.workflow_name == 'test, runnumber - ${{ github.event.inputs.environment }}'  # Change 'YOUR_WORKFLOW_NAME' to your actual workflow name
        run: |
          TOKEN=${{ secrets.GIT_ACCESSTOKEN }}
          WORKFLOW_NAME="${{ env.workflow_name }}"
          REPO="${{ github.repository }}"
          
          # Fetch the previous run number
          RESPONSE=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW_NAME/runs?per_page=2")
          PREVIOUS_RUN_NUMBER=$(echo $RESPONSE | jq -r '.workflow_runs[1].run_number')
          
          if [ "$PREVIOUS_RUN_NUMBER" != "null" ]; then
            echo "Previous run number is: $PREVIOUS_RUN_NUMBER"
            echo "previous_run_number=$PREVIOUS_RUN_NUMBER" >> $GITHUB_ENV
          else
            echo "No previous run found for the specified workflow."
          fi
