run-name: test, runnumber - ${{ github.event.inputs.environment }}
'on': 
 workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'development'

jobs:
    deploy:
     runs-on: ubuntu-latest
        
     steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_ACCESSTOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const environment = '${{ github.event.inputs.environment }}';
            const dynamicWorkflowName = `test, runnumber - ${environment}`;
 
            try {
              // Get the list of workflow runs for the repository
              const { data: runs } = await github.actions.listWorkflowRunsForRepo({
                owner,
                repo,
                per_page: 5,
                status: 'completed', // Only completed runs
              });
 
              // Filter runs based on dynamic name and event type
              const envRuns = runs.workflow_runs.filter(run =>
                run.name === dynamicWorkflowName &&
                (run.event === 'workflow_dispatch' || run.event === 'schedule')
              );
 
              // Check if any runs match
              if (envRuns.length > 0) {
                // Get the most recent run
                const previousRunId = envRuns[0].id;
 
                // Get the details for that run
                const { data: previousRunDetails } = await github.actions.getWorkflowRun({
                  owner,
                  repo,
                  run_id: previousRunId,
                });
 
                // Extract the run number
                const previousRunNumber = previousRunDetails.run_number;
                console.log(`Found previous run number: ${previousRunNumber}`);
                return previousRunNumber; // Return the run number
              } else {
                throw new Error('No previous run found for the specified environment.');
              }
            } catch (error) {
              console.error(`Error retrieving previous run: ${error.message}`);
              throw error; // Rethrow the error for the workflow to fail
            }
 
      - name: Echo Previous Run Number
        run: echo "The previous run number for ${{ github.event.inputs.environment }} is ${{ steps.get_previous_run.outputs.result }}"
