name: Android
on:
  workflow_dispatch: {}

jobs:
  Push-artifact:
   runs-on: windows-latest
   steps:
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate build number
        uses: onyxmueller/build-tag-number@v1
        with:
         token: ${{secrets.github_token}} 

      - name: Manual QA
        run: |
            echo "Manual QA build"
            echo "BUILD_NUMBER=${{ env.BUILD_NUMBER }}" >> $env:GITHUB_ENV

      - name: Version Name
        run: |
          $VERSION_NAME="24.04.001"
          "VERSION_NAME=$VERSION_NAME" >> $env:GITHUB_ENV
        
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            const refName = 'tags/v.${{ env.VERSION_NAME }}.${{ env.BUILD_NUMBER }}'
            const tagListData = await github.rest.git.listMatchingRefs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: refName
            })
            const tagList = tagListData.data
            console.log(tagList)
            if (tagList.length > 0)
            {
              console.log("Tag already exists.")
              return
            }
            else
            {
              console.log("Creating a new tag.")
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/' + refName,
                sha: context.sha
              })
            }
            
      - name: Get Previous Tag
        run: |
          $BUILD_NUMBER = $env:BUILD_NUMBER 
          $PREVIOUS_BUILDNUMBER = $($BUILD_NUMBER -1)
          $PREVIOUS_TAG = git tag --sort=-v:refname | where-object { $_ -match "v.$env:VERSION_NAME.$PREVIOUS_BUILDNUMBER" }
          Write-output "prev tag: $PREVIOUS_TAG"
          "PREVIOUS_TAG=$PREVIOUS_TAG" >> $env:GITHUB_ENV
          
      # - name: Print 
      #   run: |
      #     echo "Prev Tag: ${{ env.Previous_Tag }}"
          
      - name: Get current Tag
        run: |
         $TAG_PATTERN = "v.$env:VERSION_NAME.$env:BUILD_NUMBER"
         $TAGS = git tag --list "v.*"
         $CURRENT_TAG = $TAGS | Where-Object { $_ -like $TAG_PATTERN } | Sort-Object -Descending | Select-Object -First 1
         Write-output "Current tag: $CURRENT_TAG"
         echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $env:GITHUB_ENV
         
        
      - name: Change log
        run: |
         git log --pretty=format:"%h %s" ${{ env.PREVIOUS_TAG }}..${{ env.CURRENT_TAG }}
         
         
